pipelines:
    custom:
      vpc:
        - step:
            name: VPC Deploy
            image: hashicorp/terraform:full
            deployment: Production
            script:
                - sed -i -e "4i $VPC_BACKEND" backend.tf
                - sh deploy.sh